name: Deploy to Vercel

on:
  push:
    branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Request-Approval:
    runs-on: ubuntu-latest
    environment:
      name: production-approval
      url: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
    steps:
      - name: Send Deployment Approval Request
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Deployment Approval Required"
          body: |
            New changes have been pushed to main branch.
            Please review and approve the deployment.
            
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            
            Please approve the deployment at:
            ${{ github.server_url }}/${{ github.repository }}/actions/workflows/vercel-deploy.yml
            
            Commit URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
            
            Note: Deployment will proceed after approval from any one approver.
          to: |
            ${{ secrets.APPROVER_EMAIL_1}}
            ${{ secrets.APPROVER_EMAIL_2 }}
          from: GitHub Actions

      - name: Create Deployment Check
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.sha;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Create a deployment status check
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: 'pending',
              description: 'Waiting for deployment approval',
              context: 'Deployment Approval'
            });

  Deploy-Production:
    needs: Request-Approval
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Deployment Status
        uses: actions/github-script@v6
        with:
          script: |
            const sha = context.sha;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Update the deployment status to success
            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: 'success',
              description: 'Deployment approved',
              context: 'Deployment Approval'
            });

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Send Deployment Success Notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Deployment Successful"
          body: |
            The deployment to production was successful!
            
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
            Deployment URL: ${{ steps.deploy.outputs.url }}
            
            You can view the deployment at:
            ${{ steps.deploy.outputs.url }}
          to: |
            ${{ secrets.APPROVER_EMAIL_1}}
            ${{ secrets.APPROVER_EMAIL_2 }}
          from: GitHub Actions
